version: '3.1'
services:
  wishie-postgres-db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wishie
    volumes:
      - wishie-volume:/var/lib/postgresql/data
volumes:
  wishie-volume: